module.exports = [
  { name: 'ACCESS BANK PLC', code: 'ACC' },
  { name: 'CITIBANK NIGERIA PLC', code: 'CBN' },
  { name: 'DIAMOND BANK PLC', code: 'DMB' },
  { name: 'ECOBANK NIGERIA PLC', code: 'EBN' },
  { name: 'ENTERPRISE BANK', code: 'EPB' },
  { name: 'FIDELITY BANK PLC', code: 'FDB' },
  { name: 'FIRST BANK NIGERIA LIMITED', code: 'FBN' },
  { name: 'FIRST CITY MONUMENT BANK PLC', code: 'FCB' },
  { name: 'GUARANTY TRUST BANK PLC', code: 'GTB' },
  { name: 'HERITAGE BANK PLC', code: 'HTB' },
  { name: 'KEY STONE BANK', code: 'KSB' },
  { name: 'MAINSTREET BANK', code: 'MSB' },
  { name: 'SKYE BANK PLC', code: 'SKB' },
  { name: 'STANBIC IBTC BANK LTD', code: 'SIB' },
  { name: 'STANDARD CHARTERED BANK NIGERIA LTD', code: 'SCB' },
  { name: 'STERLING BANK PLC', code: 'STB' },
  { name: 'SUNTRUST BANK NIGERIA LTD', code: 'SBN' },
  { name: 'UNION BANK OF NIGERIA PLC', code: 'UBN'},
  { name: 'UNITED BANK FOR AFRICA PLC', code: 'UBA' },
  { name: 'UNITY BANK PLC', code: 'UNB' },
  { name: 'WEMA BANK PLC', code: 'WEM' },
  { name: 'ZENITH BANK PLC', code: 'ZIB' },
  { name: 'JAIZ BANK PLC', code: 'JAIZ' }
];
