module.exports = [
  { name: 'ACCESS BANK PLC', code: '044', slug: 'ACC', ussdCode: '*901#' },
  { name: 'CITIBANK NIGERIA PLC', code: '023', slug: 'CBN', ussdCode: null },
  { name: 'DIAMOND BANK PLC', code: '063', slug: 'DMB', ussdCode: '*710#' },
  { name: 'ECOBANK NIGERIA PLC', code: '050', slug: 'EBN', ussdCode: '*326#' },
  { name: 'ENTERPRISE BANK', code: '084', slug: 'EPB', ussdCode: '*901#' },
  { name: 'FIDELITY BANK PLC', code: '070', slug: 'FDB', ussdCode: '*770#' },
  { name: 'FIRST BANK NIGERIA LIMITED', code: '011', slug: 'FBN', ussdCode: '*894#' },
  { name: 'FIRST CITY MONUMENT BANK PLC', code: '214', slug: 'FCB', ussdCode: '*329#' },
  { name: 'GUARANTY TRUST BANK PLC', code: '058', slug: 'GTB', ussdCode: '*737#' },
  { name: 'HERITAGE BANK PLC', code: '030', slug: 'HTB', ussdCode: '*322#' },
  { name: 'KEY STONE BANK', code: '082', slug: 'KSB', ussdCode: '*533#' },
  { name: 'MAINSTREET BANK', code: '014', slug: 'MSB', ussdCode: null },
  { name: 'POLARIS BANK LIMITED', code: '076', slug: 'PLB', ussdCode: null },
  { name: 'PROVIDUS BANK LIMITED', code: '101', slug: 'PVB', ussdCode: null },
  { name: 'STANBIC IBTC BANK LTD', code: '221', slug: 'SIB', ussdCode: '*909#' },
  { name: 'STANDARD CHARTERED BANK NIGERIA LTD', code: '068', slug: 'SCB', ussdCode: null },
  { name: 'STERLING BANK PLC', code: '232', slug: 'STB', ussdCode: '*901#' },
  { name: 'SUNTRUST BANK NIGERIA LTD', code: '100', slug: 'SBN', ussdCode: null },
  { name: 'UNION BANK OF NIGERIA PLC', code: '032', slug: 'UBN', ussdCode: '*826#' },
  { name: 'UNITED BANK FOR AFRICA PLC', code: '033', slug: 'UBA', ussdCode: '*919#' },
  { name: 'UNITY BANK PLC', code: '215', slug: 'UNB', ussdCode: '*7799#' },
  { name: 'WEMA BANK PLC', code: '035', slug: 'WEM', ussdCode: '*945#' },
  { name: 'ZENITH BANK PLC', code: '057', slug: 'ZIB', ussdCode: '*966#' }
];
